#Crowd Human yaml
NAMES:
  NAME: MOT20

PATHS:
  DATASET: "D://BanYanDeng/MOTDataset"
  MODEL_SAVE_DIR: "../output/models/MOT20_DETECT_ONLY"
  RESULT_ROOT: "../output/results/MOT20_DETECT_ONLY"
  EVAL_ROOT: "../output/evaluation/MOT20_DETECT_ONLY"

WARMUP:
  SUBNET: ['backbone', 'detect_head']
  EPOCHS: 3
  MAX_LR: 0.00258
  LR_GAMMA: 0.5
  OPTIM_NAME: "Adam"  # "SGD" or "Adam"
  LR_SCHEDULER: 'MultiStep'  # 'OneCycle' or 'MultiStep'
  LR_MILESTONES: [2, 4, 8]  # 'MultiStep' LR scheduler Milestone
  GRAD_CLIP: 3.
  DIV_FACTOR: 5    # 'OneCycle' LR scheduler parameter
  FINAL_DIV_FACTOR: 10     # 'OneCycle' LR scheduler parameter
  PCT_START: 0.2
  MOMENTUM: 0.937
  WEIGHT_DECAY: 0.00058

TRAINING:
  # data setting
  BATCH_SIZE: 4
  WORKERS: 0
  SPLIT_LEN: 6
  SPLIT_BATCH_SIZE: 1
  # super parameters
  EPOCHS: 15
  MAX_LR: 0.00258
  LR_MILESTONES: [2, 4, 8, 16]
  WEIGHT_DECAY: 0.00058
  DIV_FACTOR: 10
  FINAL_DIV_FACTOR: 20
  LR_GAMMA: 0.7
  MOMENTUM: 0.937

  # Model setting
  BACKBONE_NAME: "dla"  # "default", "resnet18", " resnet34", 'dla'
  BOX_NUM: 3  # Detect boxes number of every point
  SUBNET: ['backbone', 'detect_head', 'level_split', 'adaptive_head', 'memory_head']

  # pre-transform
  IMG_MEAN: [0., 0., 0.]
  IMG_STD: [1., 1., 1.]
  IMG_MIN_SIZE: [544, 608, 672, 704]
  IMG_MAX_SIZE: 1248
  MIN_AREA: 100.   # filter targets less than 16. * 16. in size
  LEVEL_NUM: 1
  LEVEL_CHANNEL: 512
  SAVE_LEVELS: True
  SUBNET_MODE: DETECT_ONLY
  ROTATION_MAX_ANGLE: 12.
  ROTATION_MIN_SCALE: 0.75
  HGAIN: 0.015
  VGAIN: 0.7
  SGAIN: 0.4
  SPLIT_LEVEL_BY_VIS: False

  # Label setting
  LABEL_RADIUS: 0
  BOX_LABEL_FUNC: default   # default, patch

  # loss setting
  HEAT_MAP_LOSS:
    LOSS_FUNC: focal  # focal, MSE
    FOCAL_ALPHA: 0.15
    FOCAL_BASE_ALPHA: 0.
    BASE_WEIGHT: 1.  # loss weight

  BOX_LOSS:
    BASE_WEIGHT: 1.
    EPS: 1e-5

  MEMORY_LOSS:
    FOCAL_BASE_ALPHA: 0.
    FOCAL_ALPHA: 0.15
    BASE_WEIGHT: 1.  # loss weight

  # other
  PRINT_FREQ: 100
  VISUAL_FREQ: 100
  SAVE_FREQ: 5
  RANDOM_SEED: 19990320
  ENABLE_AUTOCAST: True   # True, False
  SCALE_FACTOR: 32  # backbone down sample rate
  CLAMP_EPS: 1e-5


