#Crowd Human yaml
NAMES:
  NAME: MOT20

PATHS:
  DATASET: "D://BanYanDeng/MOTDataset"
  MODEL_SAVE_DIR: "../output/models/MOT20"
  RESULT_ROOT: "../output/results/MOT20"
  EVAL_ROOT: "../output/evaluation/MOT20"

WARMUP:
  SUBNET: ['detect_head', 'level_split', 'adaptive_head', 'predict_head', 'backbone']
  EPOCHS: 3
  MAX_LR: 0.0001
  LR_GAMMA: 0.5
  OPTIM_NAME: "Adam"  # "SGD" or "Adam"
  LR_SCHEDULER: 'MultiStep'  # 'OneCycle' or 'MultiStep'
  LR_MILESTONES: [2, 4, 8]  # 'MultiStep' LR scheduler Milestone
  GRAD_CLIP: 3.
  DIV_FACTOR: 5    # 'OneCycle' LR scheduler parameter
  FINAL_DIV_FACTOR: 10     # 'OneCycle' LR scheduler parameter
  PCT_START: 0.2
  MOMENTUM: 0.937
  WEIGHT_DECAY: 0.00058

TRAINING:
  # data setting
  BATCH_SIZE: 3
  SPLIT_BATCH_SIZE: 1
  WORKERS: 0
  SPLIT_LEN: 5
  OUTPUT_DELTA_BOXES: False # delta of target's box between t frame and t + 1 frame

  # super parameters
  EPOCHS: 10
  MAX_LR: 0.0001
  LR_MILESTONES: [2, 4, 8]
  WEIGHT_DECAY: 0.00058
  DIV_FACTOR: 10
  FINAL_DIV_FACTOR: 20
  LR_GAMMA: 0.5
  MOMENTUM: 0.92

  # Model setting
  DROP_OUT_RATE: 0.2
  BACKBONE_NAME: "default"  # "default", "resnet18", " resnet34"
  ADAPTIVE_MODE: 'adaptive'  # None, 'adaptive'
  BOX_NUM: 3  # Detect boxes number of every point
  SUBNET: ["all"]

  # pre-transform
  IMG_MEAN: [0., 0., 0.]
  IMG_STD: [1., 1., 1.]
  IMG_MIN_SIZE: [544, 608, 672, 704]
  IMG_MAX_SIZE: 1248
  MIN_AREA: 100.   # filter targets less than 10. * 10. in size
  LEVEL_NUM: 4
  ROTATION_MAX_ANGLE: 12.
  ROTATION_MIN_SCALE: 0.75
  HGAIN: 0.015
  VGAIN: 0.704
  SGAIN: 0.36

  # Label setting
  LABEL_RADIUS: 0
  BOX_LABEL_FUNC: default   # default, patch

  # loss setting
  HEAT_MAP_LOSS:
    LOSS_FUNC: focal  # focal, MSE
    FOCAL_ALPHA: 1.5
    BASE_WEIGHT: 1.  # loss weight

  BOX_LOSS:
    BASE_WEIGHT: 1.
    EPS: 1e-5

  # other
  PRINT_FREQ: 100
  VISUAL_FREQ: 100
  SAVE_FREQ: 5
  RANDOM_SEED: 19990320
  ENABLE_AUTOCAST: True   # True, False
  SCALE_FACTOR: 16  # backbone down sample rate
  CLAMP_EPS: 1e-5


