# MOT17SDP yaml
NAMES:
  NAME: MOT17

PATHS:
  DATASET: "D://BanYanDeng/MOTDataset"
  MODEL_SAVE_DIR: "../output/models/MOT17SDP"
  LOG_ROOT: "../output/Logs/MOT17SDP"
  EVAL_ROOT: "../output/evaluation/MOT17SDP"

WARMUP:
  SUBNET: ['backbone', 'detect_head']
  EPOCHS: 5
  MAX_LR: 0.0002
  LR_GAMMA: 0.5
  OPTIM_NAME: "Adam"  # "SGD" or "Adam"
  LR_SCHEDULER: 'MultiStep'  # 'OneCycle' or 'MultiStep'
  LR_MILESTONES: [2, 4, 8]  # 'MultiStep' LR scheduler Milestone
  GRAD_CLIP: 3.
  DIV_FACTOR: 5    # 'OneCycle' LR scheduler parameter
  FINAL_DIV_FACTOR: 10     # 'OneCycle' LR scheduler parameter
  PCT_START: 0.2
  MOMENTUM: 0.937
  WEIGHT_DECAY: 0.000058

TRAINING:
  # data setting
  BATCH_SIZE: 4
  WORKERS: 0
  SPLIT_LEN: 5
  SPLIT_BATCH_SIZE: 1
  # super parameters
  EPOCHS: 30
  MAX_LR: 0.00025
  LR_MILESTONES: [2, 4, 8, 16]
  WEIGHT_DECAY: 0.0
  OPTIM_NAME: "SGD"  # "SGD" or "Adam"
  LR_SCHEDULER: StepLR  # 'OneCycle' or 'MultiStep' or 'StepLR'
  DIV_FACTOR: 10
  FINAL_DIV_FACTOR: 200
  LR_GAMMA: 0.5
  GRAD_CLIP: 3.
  MOMENTUM: 0.937
  STEP_SIZE: 3

  # Model setting
  MODEL_NAME: "MainModel"
  BACKBONE_NAME: "dla"  # "default", "resnet18", " resnet34", 'dla'
  CLS_NUM: 3  #
  SUBNET: ['backbone', 'detect_head']
  BRIDGE_KERNEL: []
  TRAIN_MEMORY: True

  # pre-transform
  IMG_MEAN: [0., 0., 0.]
  IMG_STD: [1., 1., 1.]
  IMG_MIN_SIZE: [640]
  IMG_MAX_SIZE: 1248
  MIN_AREA: 100.   # filter targets less than 10. * 10. in size
  LEVEL_NUM: 2
  LEVEL_CHANNEL: 128
  SUBNET_MODE: ""
  ROTATION_MAX_ANGLE: 12.
  ROTATION_MIN_SCALE: 0.7
  HGAIN: 0.015
  VGAIN: 0.7
  SGAIN: 0.4

  # Label setting
  BOX_LABEL_FUNC: default   # default, patch
  LABEL_MIN_OVERLAP_RATIO: 0.5

  # loss setting
  HEAT_MAP_LOSS:
    BASE_WEIGHT: 1.5  # loss weight

  BOX_LOSS:
    BASE_WEIGHT: 1.

  MEMORY_LOSS:
    BASE_WEIGHT: 1.  # loss weight

  REID_LOSS:
    BASE_WEIGHT: 1.
    FUNC: "ce"  # crossEntropyLoss, focal

  # other
  PRINT_FREQ: 100
  VISUAL_FREQ: 100
  SAVE_FREQ: 5
  RANDOM_SEED: 990320
  ENABLE_AUTOCAST: True   # True, False
  SCALE_FACTOR: 8  # backbone down sample rate
  CLAMP_EPS: 1e-5
  GRADIENT_ACU_FRQ: 4   # gradient accumulate frequency



